name: Push Hugo static site to priyavrat-misra/priyavrat-misra.github.io

on:
  push:
    branches: [ main ]

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.150.0
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/jod'
          cache: 'npm'
      - name: Install Node Dependencies
        run: npm install
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          hugo build --minify --gc
      - name: Push Hugo output to priyavrat-misra/priyavrat-misra.github.io
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          # GitHub Action output files
          source-directory: 'public'
          destination-github-username: 'priyavrat-misra'
          destination-repository-name: 'priyavrat-misra.github.io'
          user-name: 'github-actions[bot]'
          user-email: '41898282+github-actions[bot]@users.noreply.github.com'
          target-branch: main
      - name: Test get variable exported by priyavrat-misra.github.io
        run: echo $DESTINATION_CLONED_DIRECTORY
