name: Push Hugo static site to priyavrat-misra/priyavrat-misra.github.io

on:
  push:
    branches: [ main ]

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.145.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Push Hugo output to priyavrat-misra/priyavrat-misra.github.io
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          # GitHub Action output files
          source-directory: 'public'
          destination-github-username: 'priyavrat-misra'
          destination-repository-name: 'priyavrat-misra.github.io'
          user-name: 'Priyavrat Misra'
          user-email: 'priyavratmisra123@gmail.com'
          target-branch: main
      - name: Test get variable exported by priyavrat-misra.github.io
        run: echo $DESTINATION_CLONED_DIRECTORY
